find_package(benchmark)
find_package(GSL REQUIRED)
find_package(PCL REQUIRED COMPONENTS common filters io segmentation)
find_package(fmt REQUIRED)
find_package(range-v3 REQUIRED)
find_package(spdlog REQUIRED)

if(ENABLE_ROS2BAG_OUTPUT)
    find_package(rclcpp REQUIRED)
    find_package(rosbag2_cpp REQUIRED)
    find_package(sensor_msgs REQUIRED)
endif()
